application: pixedus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/ico
  static_dir: static/ico
- url: /static/img
  static_dir: static/img
- url: /static/js
  static_dir: static/js
- url: /static/less
  static_dir: static/less
- url: /static/xml
  static_dir: static/xml
- url: /sitemap.xml
  static_files: static/xml/sitemap.xml
  upload: static/xml/sitemap.xml
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest